version: '2'

# Define the services/containers to be run
services:
  express:
    build: .
    environment:
      - DATABASE_URL=mongodb://mongo:27017
    ports:
      - "3000:3000" 
    links: ['mongo']
  mongo:
    image: mongo
    ports:
      - "27017:27017"